excerpt_separator: ""
highlighter: pygments
markdown: kramdown
url: http://vishalsinha21.github.io
title: My Notes
tagline: some of this and some of that
description: Vishal Sinha's Blog
paginate: 5